In [1]:
import numpy as np 
import pandas as pd 

In [2]:
df = pd.read_csv('Downloads/icml_face_data.csv')

In [3]:
print(df.head(10))

   emotion     Usage                                             pixels
0        0  Training  70 80 82 72 58 58 60 63 54 58 60 48 89 115 121...
1        0  Training  151 150 147 155 148 133 111 140 170 174 182 15...
2        2  Training  231 212 156 164 174 138 161 173 182 200 106 38...
3        4  Training  24 32 36 30 32 23 19 20 30 41 21 22 32 34 21 1...
4        6  Training  4 0 0 0 0 0 0 0 0 0 0 0 3 15 23 28 48 50 58 84...
5        2  Training  55 55 55 55 55 54 60 68 54 85 151 163 170 179 ...
6        4  Training  20 17 19 21 25 38 42 42 46 54 56 62 63 66 82 1...
7        3  Training  77 78 79 79 78 75 60 55 47 48 58 73 77 79 57 5...
8        3  Training  85 84 90 121 101 102 133 153 153 169 177 189 1...
9        2  Training  255 254 255 254 254 179 122 107 95 124 149 150...


In [4]:
print(df.columns)

Index(['emotion', ' Usage', ' pixels'], dtype='object')


In [5]:
df.columns = ['emotion','Usage','pixels']

In [6]:
train_samples = df[df['Usage']=="Training"]

In [7]:
test_samples = df[df['Usage']=="PrivateTest"]

In [8]:
X_train =np.array([ np.fromstring(image, np.uint8, sep=" ") for image in train_samples.pixels])
X_test =np.array([ np.fromstring(image, np.uint8, sep=" ") for image in test_samples.pixels])

In [9]:
y_train = train_samples.emotion.astype(np.int32).values
y_test = test_samples.emotion.astype(np.int32).values

In [10]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler 
from sklearn.svm import LinearSVC
from sklearn.preprocessing import PolynomialFeatures

In [11]:
from sklearn.svm import SVC
polynomial_kernel_svm_classifier = Pipeline([("scaler",StandardScaler()),
                                ("svm_clf",SVC(kernel="poly",degree=3,decision_function_shape="ovo",coef0=1, C=0.5,verbose=True))])

In [12]:
polynomial_kernel_svm_classifier

Pipeline(memory=None,
         steps=[('scaler',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('svm_clf',
                 SVC(C=0.5, cache_size=200, class_weight=None, coef0=1,
                     decision_function_shape='ovo', degree=3,
                     gamma='auto_deprecated', kernel='poly', max_iter=-1,
                     probability=False, random_state=None, shrinking=True,
                     tol=0.001, verbose=True))],
         verbose=False)

In [13]:
polynomial_kernel_svm_classifier.fit(X_train,y_train)

[LibSVM]

Pipeline(memory=None,
         steps=[('scaler',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('svm_clf',
                 SVC(C=0.5, cache_size=200, class_weight=None, coef0=1,
                     decision_function_shape='ovo', degree=3,
                     gamma='auto_deprecated', kernel='poly', max_iter=-1,
                     probability=False, random_state=None, shrinking=True,
                     tol=0.001, verbose=True))],
         verbose=False)

In [15]:
Y_pred = polynomial_kernel_svm_classifier.predict(X_test)

In [16]:
Y_pred

array([0, 0, 4, ..., 3, 4, 4], dtype=int32)

In [17]:
y_test

array([0, 5, 6, ..., 0, 3, 2], dtype=int32)

In [18]:
from sklearn.metrics import accuracy_score

In [19]:
accuracy_score(y_test, Y_pred)

0.4653106714962385

In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [22]:
df = pd.read_csv("Downloads/fer2013.csv")
df.head(3)

emotion                                             pixels     Usage
0        0  70 80 82 72 58 58 60 63 54 58 60 48 89 115 121...  Training
1        0  151 150 147 155 148 133 111 140 170 174 182 15...  Training
2        2  231 212 156 164 174 138 161 173 182 200 106 38...  Training

In [23]:
train = df[["emotion", "pixels"]][df["Usage"] == "Training"]

In [24]:
train['pixels'] = train['pixels'].apply(lambda im: np.fromstring(im, sep=' '))

In [25]:
x_train = np.vstack(train['pixels'].values)
y_train = np.array(train["emotion"])

In [26]:
x_train.shape, y_train.shape# Facial Expression Detection with nonliner SVM (kernel = rbf) of regularization parameter (C) = 10

((28709, 2304), (28709,))

In [27]:
x_train

array([[ 70.,  80.,  82., ..., 106., 109.,  82.],
       [151., 150., 147., ..., 193., 183., 184.],
       [231., 212., 156., ...,  88., 110., 152.],
       ...,
       [ 74.,  81.,  87., ..., 188., 187., 187.],
       [222., 227., 203., ..., 136., 136., 134.],
       [195., 199., 205., ...,   6.,  15.,  38.]])

In [28]:
y_train

array([0, 0, 2, ..., 4, 0, 4])

In [29]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)

In [30]:
x_train

array([[-0.60988232, -0.45922179, -0.40324932, ..., -0.08629621,
        -0.05737476, -0.41127695],
       [ 0.37236201,  0.40461631,  0.41101767, ...,  1.0387427 ,
         0.89140538,  0.88666892],
       [ 1.34247986,  1.16973007,  0.52376233, ..., -0.31906288,
        -0.04455341,  0.47947022],
       ...,
       [-0.56137642, -0.44688125, -0.3406134 , ...,  0.97408529,
         0.94269079,  0.9248438 ],
       [ 1.2333416 ,  1.35483823,  1.11254   , ...,  0.30164824,
         0.28880177,  0.25042095],
       [ 0.90592683,  1.00930299,  1.13759436, ..., -1.37944439,
        -1.26258197, -0.97117517]])

In [31]:
public_test_df = df[["emotion", "pixels"]][df["Usage"]=="PrivateTest"]

In [32]:
public_test_df["pixels"] = public_test_df["pixels"].apply(lambda im: np.fromstring(im, sep=' '))
x_test = np.vstack(public_test_df["pixels"].values)
y_test = np.array(public_test_df["emotion"])

In [33]:
x_test.shape, y_test.shape

((3589, 2304), (3589,))

In [34]:
x_test = scaler.fit_transform(x_test)

In [35]:
x_test

array([[ 0.61775376,  0.03013668, -0.14355808, ...,  0.6047927 ,
         0.25792794,  0.2145329 ],
       [-1.34508636, -1.35969043, -1.31165215, ..., -0.51088765,
        -0.70735192, -0.78195679],
       [ 1.36435552,  1.53065797,  1.61486309, ..., -1.38291367,
        -1.38050762, -1.3243499 ],
       ...,
       [-1.22466672, -1.21209817, -1.21117094, ...,  0.54067314,
         0.25792794, -0.01251539],
       [-1.06812119, -1.07680527, -1.06044913, ..., -0.9853724 ,
        -1.0502803 , -1.08468783],
       [-1.2005828 , -1.26129559, -1.23629124, ...,  0.98951006,
         1.0961973 ,  1.09749844]])

In [36]:
y_test

array([0, 5, 6, ..., 0, 3, 2])

In [37]:
from sklearn.metrics import accuracy_score, matthews_corrcoef, confusion_matrix
from sklearn.svm import SVC

In [ ]:
model = SVC(C=10, kernel='rbf')
model.fit(x_train,y_train)
y_pred = model.predict(x_test)
print("Accuracy on test set:   ", accuracy_score(y_test,y_pred))
confusion = confusion_matrix(y_test,y_pred)
print(confusion)
print("MCC:   ", matthews_corrcoef(y_test,y_pred))

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
clf = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0,max_depth=1, random_state=0).fit(x_train,y_train)